#pragma once
#include "Engine/Input//KeyButtonState.hpp"

enum KeyBoardButtonID {
	KEYBOARD_BUTTON_ID_INVALID		= -1,
	KEYBOARD_BUTTON_ID_BACK			= 8,
	KEYBOARD_BUTTON_ID_ENTER		= 13,
	KEYBOARD_BUTTON_ID_SHIFT		= 16,
	KEYBOARD_BUTTON_ID_ESC			= 27,
	KEYBOARD_BUTTON_ID_SPACE		= 32,
	KEYBOARD_BUTTON_ID_LEFT_ARROW	= 37,
	KEYBOARD_BUTTON_ID_UP_ARROW,
	KEYBOARD_BUTTON_ID_RIGHT_ARROW,
	KEYBOARD_BUTTON_ID_DOWN_ARROW,
	KEYBOARD_BUTTON_ID_DELETE		= 46,
	KEYBOARD_BUTTON_ID_0			= 48,
	KEYBOARD_BUTTON_ID_1,
	KEYBOARD_BUTTON_ID_2,
	KEYBOARD_BUTTON_ID_3,
	KEYBOARD_BUTTON_ID_4,
	KEYBOARD_BUTTON_ID_5,
	KEYBOARD_BUTTON_ID_6,
	KEYBOARD_BUTTON_ID_7,
	KEYBOARD_BUTTON_ID_8,
	KEYBOARD_BUTTON_ID_9,
	KEYBOARD_BUTTON_ID_A			= 65,
	KEYBOARD_BUTTON_ID_B,
	KEYBOARD_BUTTON_ID_C,
	KEYBOARD_BUTTON_ID_D,
	KEYBOARD_BUTTON_ID_E,
	KEYBOARD_BUTTON_ID_F,
	KEYBOARD_BUTTON_ID_G,
	KEYBOARD_BUTTON_ID_H,
	KEYBOARD_BUTTON_ID_I,
	KEYBOARD_BUTTON_ID_J,
	KEYBOARD_BUTTON_ID_K,
	KEYBOARD_BUTTON_ID_L,
	KEYBOARD_BUTTON_ID_M,
	KEYBOARD_BUTTON_ID_N,
	KEYBOARD_BUTTON_ID_O,
	KEYBOARD_BUTTON_ID_P,
	KEYBOARD_BUTTON_ID_Q,
	KEYBOARD_BUTTON_ID_R,
	KEYBOARD_BUTTON_ID_S,
	KEYBOARD_BUTTON_ID_T,
	KEYBOARD_BUTTON_ID_U,
	KEYBOARD_BUTTON_ID_V,
	KEYBOARD_BUTTON_ID_W,
	KEYBOARD_BUTTON_ID_X,
	KEYBOARD_BUTTON_ID_Y,
	KEYBOARD_BUTTON_ID_Z,
	KEYBOARD_BUTTON_ID_F1			= 112,
	KEYBOARD_BUTTON_ID_F2,
	KEYBOARD_BUTTON_ID_F3,
	KEYBOARD_BUTTON_ID_F4,
	KEYBOARD_BUTTON_ID_F5,
	KEYBOARD_BUTTON_ID_F6,
	KEYBOARD_BUTTON_ID_F7,
	KEYBOARD_BUTTON_ID_F8,
	KEYBOARD_BUTTON_ID_SEMICOLON	= 186,
	KEYBOARD_BUTTON_ID_PLUS			= 187,
	KEYBOARD_BUTTON_ID_COMMA,
	KEYBOARD_BUTTON_ID_MINUS,
	KEYBOARD_BUTTON_ID_PERIOD,
	KEYBOARD_BUTTON_ID_TILDE		= 192,
	KEYBOARD_BUTTON_ID_LEFT_BRACKET = 219,
	KEYBOARD_BUTTON_ID_BACKSLASH,
	KEYBOARD_BUTTON_ID_RIGHT_BRACKET = 221, 
	NUM_KEYBOARD_BUTTONS
};

class KeyBoardController {
	friend class InputSystem;

public:
	KeyBoardController(){}
	~KeyBoardController(){}

	const KeyButtonState& GetButtonState(KeyBoardButtonID buttonID) const;

private:
	void UpdateButtonCurrentFrame( unsigned char inputButton, bool isPressed );
	void UpdateButtonsLastFrame();
	void InitialButtonStates();

public:
	KeyButtonState m_buttonStates[NUM_KEYBOARD_BUTTONS];

};